session13/project/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    # /accounts/
    path('', views.home, name = 'home'),
    path('base', views.base, name='base'),
]

session13/project/blog/urls.py
from django.urls import path, include
from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.home, name="home"),
    path('base', views.base, name='base'),
    path('new/', views.new, name="new"),
    path('detail/<int:post_pk>/', views.detail, name="detail"),
    path('update/<int:post_pk>/', views.update, name="update"),
    path('delete/<int:post_pk>/', views.delete, name="delete"),
    path("registration/signup/", views.signup, name="signup"),
    path("registration/login/", views.login, name="login"),
    path("registration/logout/", views.logout, name="logout"),
]

session13/project/project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
]

session13/project/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveIntegerField(help_text="User Age", blank=True, null=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='profiles')

session13/project/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    content = models.TextField()
    create_dt = models.DateTimeField(auto_now_add=True)
    update_dt = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_posts", null=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        ordering = ('-create_dt', 'author')

    def __str__(self):
        return f'{self.title}입니다.'
    
    def get_absolute_url(self):
        return reverse(f'blog:post_detail', args=[self.id])
    
    def get_previous(self):
        return self.get_previous_by_create_dt()

    def get_next(self):
        return self.get_next_by_create_dt()
    
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="my_comments")
    content = models.TextField()
    create_dt = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ('-create_dt', 'post', 'author')

    def __str__(self):
        return f'{self.author}-{self.content}'

session13/project/accounts/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request, 'accounts/home.html')

def base(request):
    return render(request, 'accounts/base.html)')

session13/project/blog/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import Post

# Create your views here.
def login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        user = auth.authenticate(username=username, password=password)

        if user is not None:
            auth.login(request, user, backend="django.contrib.auth.backends.ModelBackend")
            return redirect(request.GET.get('next', '/blog/'))
        error = "아이디 또는 비밀번호가 틀립니다"
        return render(request, 'blog/registration/login.html', {"error" : error})
    
    return render(request, 'blog/registration/login.html')

def logout(request):
    auth.logout(request)
    return redirect('blog:home')

def signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']

        exist_user = User.objects.filter(username=username)

        if exist_user:
            error = "이미 존재하는 유저입니다."
            return render(request, 'blog/registration/signup.html', {"error" : error})
        
        new_user = User.objects.create_user(username=username, password=password)
        auth.login(request, new_user)
        return redirect('blog:home')
    
    return render(request, 'blog/registration/signup.html')

def base(request):
    return render(request, 'blog/base.html)')

def home(request):
    posts = Post.objects.all()

    return render(request, 'blog/home.html', {'posts' : posts})

@login_required(login_url="/blog/registration/login/")
def new (request):
    if request.method== "POST":
        new_post = Post.objects.create(
            title = request.POST['title'],
            content = request.POST['content'],
        )
        return redirect('blog:detail', new_post.pk)
    
    return render(request, 'blog/new.html')

@login_required(login_url="/blog/registration/login/")
def detail(request, post_pk):
    post = Post.objects.get(pk=post_pk)

    return render(request, 'blog/detail.html', {'post' : post})

@login_required(login_url="/blog/registration/login/")
def update(request, post_pk):
    post = Post.objects.get(pk=post_pk)

    if request.method == 'POST':
        Post.objects.filter(pk=post_pk).update(
            title = request.POST['title'],
            content = request.POST['content']
        )
        return redirect('blog:detail', post_pk)
    
    return render(request, 'blog/update.html', {'post': post})

@login_required(login_url="/blog/registration/login/")   
def delete(request, post_pk):
    post = Post.objects.get(pk=post_pk)
    post.delete()

    return redirect('blog:home')

session13/project/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}" />
    <style>ul{list-style: none; padding-left: 0px;}</style>
    {% block css %}
    {% endblock css %}
    <title>Document</title>
</head>
<body>
    <nav id="navbar">
        <div class="navbar_logo">
            <a href="{% url 'blog:home' %}">home</a>
        </div>
        <ul class="navbar_menu">
            <li class="navbar_menu_item">
                <a href="{% url 'blog:new' %}">New</a>
            </li>
            <li class="navbar_menu_item">
                <a href="{% url 'blog:home' %}">Home</a>
            </li>
            <span class="navbar_menu_item">Hello, ㅇㅇ</span>
            <li class="navbar_menu_item">
                <a href="{% url 'blog:logout' %}">Logout</a>
            </li>
            <li class="navbar_menu_item">
                <a href="{% url 'blog:login' %}">Login</a>
            </li>
            <li class="navbar_menu_item">
                <a href="{% url 'blog:signup' %}">Signup</a>
            </li>
        </ul>
    </nav>
    <div class="title">
        {% block title %}

        {% endblock title %}
    </div>
    <div class="content">
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

session13/project/accounts/templates/accounts/home.html
{% extends 'accounts/base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'accounts/home.css' %}">
{% endblock %}

{% block title %}
<h1>독후감 블로그 - 회원관리</h1>
{% endblock %}

{% block content %}
<a href="{% url 'blog:home'%}">독후감 블로그</a>
{% endblock %}

session13/project/blog/templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'base.css' %}" />
    <style>ul{list-style: none; padding-left: 0px;}</style>
    {% block css %}
    {% endblock css %}
    <title>Document</title>
</head>
<body>
    <nav id="navbar">
        <div class="navbar_logo">
            <a href="{% url 'blog:home' %}">home</a>
        </div>
        <ul class="navbar_menu">
            <li class="navbar_menu_item">
                <a href="{% url 'blog:new' %}">New</a>
            </li>
            <li class="navbar_menu_item">
                <a href="{% url 'blog:home' %}">Home</a>
            </li>
            {% if user.is_authenticated %}
            <span class="navbar_menu_item">Hello, {{user.username}}</span>
            <li class="navbar_menu_item">
                <a href="{% url 'blog:logout'%}">Logout</a>
            </li>
            {% else %}
            <li class="navbar_menu_item">
                <a href="{% url 'blog:login'%}">Login</a>
            </li>
            <li class="navbar_menu_item">
                <a href="{% url 'blog:signup'%}">Signup</a>
            </li>
            {% endif %}
        </ul>
    </nav>
    <div class="title">
        {% block title %}

        {% endblock title %}
    </div>
    <div class="content">
        {% block content %}

        {% endblock content %}
    </div>
</body>
</html>

session13/project/blog/templates/blog/detail.html
{% extends 'blog/base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'detail.css' %}">
{% endblock %}

{% block title %}
<h2>제목</h2>
<p>{{ post.title }}</p>
{% endblock %}

{% block content %}
<div>
    <h2>내용</h2>
    <p>{{ post.content}}</p>
</div>
<a href="{% url 'blog:home' %}">홈으로</a>
<a href="{% url 'blog:update' post.pk%}">수정하기</a>
<a href="{% url 'blog:delete' post.pk%}">삭제하기</a>
{% endblock %}

session13/project/blog/templates/blog/home.html
{% extends 'blog/base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'home.css' %}">
{% endblock %}

{% block title %}
<h1>독후감 블로그</h1>
{% endblock %}

{% block content %}
<div>
    <ul>
        {% for post in posts %}
        <li>
            <a href="{% url 'blog:detail' post.pk %}">{{ post.title }}</a>
        </li>
        {% endfor %}
    </ul>
</div>
<a href="{% url 'blog:new'%}">글 쓰러가기</a>
{% endblock %}

session13/project/blog/templates/blog/new.html
{% extends 'blog/base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static '.css' %}">
{% endblock %}

{% block title %}
<h1>New</h1>
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div>
        <label for="title">제목</label>
        <input type="text" id="title" name="title" placeholder="제목을 입력해주세요.">
    </div>
    <div>
        <label for="content">내용</label>
        <textaea name="content" id="content" cols="50" rows="15"></textaea>
    </div>
    <button type="submit">작성하기</button>
</form>
{% endblock %}

session13/project/blog/templates/blog/update.html
{% extends 'blog/base.html' %}

{% block css %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'update.css' %}">
{% endblock %}

{% block title %}
<h2>제목</h2>
<p>{{ post.title }}</p>
{% endblock %}

{% block content %}
<form action="" method="post">
    {% csrf_token %}
    <div>
        <label for="title">제목</label>
        <input type="text" id="title" name="title" value="{{ post.title }}">
    </div>
    <div>
        <label for="content">내용</label>
        <textarea name="content" id="content" cols="30" rows="10">{{ post.content }}</textarea>
    </div>
    <button type="submit">수정하기</button>
</form>
{% endblock %}